# Copyright (C) 2015-2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/yu/tomato/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/yu/tomato/proprietary/vendor/lib/libjpegdhw.so:system/vendor/lib/libjpegdhw.so \
    vendor/yu/tomato/proprietary/vendor/lib/libjpegehw.so:system/vendor/lib/libjpegehw.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_c2d_module.so:system/vendor/lib/libmmcamera2_c2d_module.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_cpp_module.so:system/vendor/lib/libmmcamera2_cpp_module.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:system/vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_iface_modules.so:system/vendor/lib/libmmcamera2_iface_modules.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:system/vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_is.so:system/vendor/lib/libmmcamera2_is.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_isp_modules.so:system/vendor/lib/libmmcamera2_isp_modules.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:system/vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_q3a_core.so:system/vendor/lib/libmmcamera2_q3a_core.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:system/vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:system/vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_stats_modules.so:system/vendor/lib/libmmcamera2_stats_modules.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_vpe_module.so:system/vendor/lib/libmmcamera2_vpe_module.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera2_wnr_module.so:system/vendor/lib/libmmcamera2_wnr_module.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:system/vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_imglib.so:system/vendor/lib/libmmcamera_imglib.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_imx135_cp8675.so:system/vendor/lib/libmmcamera_imx135_cp8675.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_imx214_cp8675.so:system/vendor/lib/libmmcamera_imx214_cp8675.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_ov5648_cp8675.so:system/vendor/lib/libmmcamera_ov5648_cp8675.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_sunny_imx214_eeprom.so:system/vendor/lib/libmmcamera_sunny_imx214_eeprom.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_tintless_algo.so:system/vendor/lib/libmmcamera_tintless_algo.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:system/vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmipl.so:system/vendor/lib/libmmipl.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/yu/tomato/proprietary/vendor/lib/libmmqjpeg_codec.so:system/vendor/lib/libmmqjpeg_codec.so \
    vendor/yu/tomato/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/yu/tomato/proprietary/vendor/lib/libqomx_jpegenc.so:system/vendor/lib/libqomx_jpegenc.so \
    vendor/yu/tomato/proprietary/vendor/lib/libactuator_dw9714a.so:system/vendor/lib/libactuator_dw9714a.so \
    vendor/yu/tomato/proprietary/vendor/lib/libactuator_dw9714a_camcorder.so:system/vendor/lib/libactuator_dw9714a_camcorder.so \
    vendor/yu/tomato/proprietary/vendor/lib/libactuator_dw9714a_camera.so:system/vendor/lib/libactuator_dw9714a_camera.so \
    vendor/yu/tomato/proprietary/vendor/lib/libactuator_dw9718s.so:system/vendor/lib/libactuator_dw9718s.so \
    vendor/yu/tomato/proprietary/vendor/lib/libactuator_dw9718s_camcorder.so:system/vendor/lib/libactuator_dw9718s_camcorder.so \
    vendor/yu/tomato/proprietary/vendor/lib/libactuator_dw9718s_camera.so:system/vendor/lib/libactuator_dw9718s_camera.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_common.so:system/vendor/lib/libchromatix_imx135_common.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_default_video.so:system/vendor/lib/libchromatix_imx135_default_video.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_hfr_120.so:system/vendor/lib/libchromatix_imx135_hfr_120.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_hfr_60.so:system/vendor/lib/libchromatix_imx135_hfr_60.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_hfr_90.so:system/vendor/lib/libchromatix_imx135_hfr_90.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_preview.so:system/vendor/lib/libchromatix_imx135_preview.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_snapshot.so:system/vendor/lib/libchromatix_imx135_snapshot.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx135_video_hd.so:system/vendor/lib/libchromatix_imx135_video_hd.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_1080p_ofilm.so:system/vendor/lib/libchromatix_imx214_1080p_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_24fps_snapshot_ofilm.so:system/vendor/lib/libchromatix_imx214_24fps_snapshot_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_30fps_preview_ofilm.so:system/vendor/lib/libchromatix_imx214_30fps_preview_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_30fps_snapshot_ofilm.so:system/vendor/lib/libchromatix_imx214_30fps_snapshot_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_480p_ofilm.so:system/vendor/lib/libchromatix_imx214_480p_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_4k_video_ofilm.so:system/vendor/lib/libchromatix_imx214_4k_video_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_720p_ofilm.so:system/vendor/lib/libchromatix_imx214_720p_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_common_ofilm.so:system/vendor/lib/libchromatix_imx214_common_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_hfr_120_ofilm.so:system/vendor/lib/libchromatix_imx214_hfr_120_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_hfr_60_ofilm.so:system/vendor/lib/libchromatix_imx214_hfr_60_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_hfr_90_ofilm.so:system/vendor/lib/libchromatix_imx214_hfr_90_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_liveshot_ofilm.so:system/vendor/lib/libchromatix_imx214_liveshot_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_imx214_preview_ofilm.so:system/vendor/lib/libchromatix_imx214_preview_ofilm.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_ofilm_common.so:system/vendor/lib/libchromatix_ov5648_ofilm_common.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_ofilm_default_video.so:system/vendor/lib/libchromatix_ov5648_ofilm_default_video.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_ofilm_liveshot.so:system/vendor/lib/libchromatix_ov5648_ofilm_liveshot.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_ofilm_preview.so:system/vendor/lib/libchromatix_ov5648_ofilm_preview.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_ofilm_snapshot.so:system/vendor/lib/libchromatix_ov5648_ofilm_snapshot.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_qtech_common.so:system/vendor/lib/libchromatix_ov5648_qtech_common.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_qtech_default_video.so:system/vendor/lib/libchromatix_ov5648_qtech_default_video.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_qtech_liveshot.so:system/vendor/lib/libchromatix_ov5648_qtech_liveshot.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_qtech_preview.so:system/vendor/lib/libchromatix_ov5648_qtech_preview.so \
    vendor/yu/tomato/proprietary/vendor/lib/libchromatix_ov5648_qtech_snapshot.so:system/vendor/lib/libchromatix_ov5648_qtech_snapshot.so \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/yu/tomato/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:system/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb 


